- name: Copy docker compose
  ansible.builtin.copy:
    src: docker-compose.yaml
    dest: /home/arsha/docker-compose.yaml

- name: Docker login
  community.docker.docker_login:
    registry_url: https://index.docker.io/v1/
    username: arshashiri
    password: "{{docker_password}}"

- name: Start container from compose
  community.docker.docker_compose:
    project_src: /home/arsha