---
plugin: aws_ec2
# We can have multiple regions here!
regions: 
  - eu-west-3
# This helps us to targe specific group of servers
filters:
  # All the servers that their tags start with dev
  tag:Name: dev*
# This helps us to group servers
keyed_groups:
  - key: tags
    prefix: tag
  - key: instance_type
    prefix: instance_type